import {useCallback,useEffect,useRef,useState} from 'react';
import type {CSSProperties} from 'react';
import {Activity,ArrowDown,ArrowRight,Check,ChevronDown,ChevronRight,Code2,Download,ExternalLink,History,Layers,LoaderCircle,MessageCircle,Mic,Pause,Play,Radio,RotateCcw,Settings2,ShieldCheck,SkipForward,Terminal,Volume2,VolumeX,Wifi,WifiOff,X,Zap} from 'lucide-react';
import {api,post} from './types';
import type {Config,Feed,Game,RunEvent,SavedRun,Session,Team,Turn} from './types';
import {mergeSessionView,reduceEvent} from './session';
import {BroadcastAudio} from './audio';

const asText=(value:unknown)=>typeof value==='string'?value:JSON.stringify(value,null,2);
const duration=(value:number|null|undefined)=>value==null?'—':`${Math.round(value)} ms`;
const time=(value?:string|null)=>value?new Date(value).toLocaleTimeString('en-GB',{timeZone:'Europe/Dublin',hour:'2-digit',minute:'2-digit',second:'2-digit'}):'—';
const ordinal=(value:number|null|undefined)=>value==null?'—':`${value}${value===1?'st':value===2?'nd':value===3?'rd':'th'}`;
const localDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Dublin',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const teamColor=(team?:Team):CSSProperties=>({'--team':team?.color??'#b7f344'} as CSSProperties);
function Logo({team,size=38}:{team?:Team;size?:number}){return team?<img className="team-logo" width={size} height={size} src={team.logo} alt={`${team.name} logo`} onError={e=>{e.currentTarget.style.visibility='hidden';}}/>:<span className="team-placeholder" style={{width:size,height:size}}>NFL</span>;}
function Wave({active=false}:{active?:boolean}){return <div className={`wave ${active?'active':''}`} aria-hidden="true">{Array.from({length:18},(_,i)=><i key={i} style={{height:`${[12,21,9,28,17,34,24,13,30,18,26,36,15,27,11,23,18,8][i]}px`,animationDelay:`${i*.075}s`}}/>)}</div>;}
function App(){
  const [teams,setTeams]=useState<Team[]>([]),[games,setGames]=useState<Game[]>([]),[config,setConfig]=useState<Config|null>(null);
  const [session,setSession]=useState<Session|null>(null),[saved,setSaved]=useState<SavedRun[]>([]);
  const [mode,setMode]=useState<'replay'|'live'>('replay'),[provider,setProvider]=useState<'demo'|'openai'>('demo');
  const [selectedTeam,setSelectedTeam]=useState<string|null>(null),[selectedGame,setSelectedGame]=useState('2024_01_BAL_KC');
  const [date,setDate]=useState(localDate()),[feed,setFeed]=useState<Feed>({status:'connecting'});
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [muted,setMuted]=useState(true),[speaking,setSpeaking]=useState<string|null>(null),[connected,setConnected]=useState(false);
  const [debug,setDebug]=useState(false),[debugTab,setDebugTab]=useState('timeline'),[historyOpen,setHistoryOpen]=useState(false),[help,setHelp]=useState(false);
  const [traceSelected,setTraceSelected]=useState<number|null>(null),[readingSaved,setReadingSaved]=useState(false);
  const [captions,setCaptions]=useState<Record<string,{agent_id:string;persona:string;text:string}>>({});
  const socket=useRef<WebSocket|null>(null),seq=useRef(0),epoch=useRef(0),sessionRef=useRef<Session|null>(null),mutedRef=useRef(true),savedRef=useRef(false);
  const transcriptEnd=useRef<HTMLDivElement|null>(null),audioRef=useRef<BroadcastAudio|null>(null);
  if(!audioRef.current)audioRef.current=new BroadcastAudio(setSpeaking,(id,samples,cancelled)=>{if(socket.current?.readyState===WebSocket.OPEN)socket.current.send(JSON.stringify({type:'playback.ack',segment_id:id,played_samples:samples,cancelled}));});
  const findTeam=useCallback((id?:string|null)=>teams.find(t=>t.id===id||t.abbreviation===id),[teams]);
  useEffect(()=>{sessionRef.current=session;},[session]);
  useEffect(()=>{mutedRef.current=muted;},[muted]);
  useEffect(()=>{savedRef.current=readingSaved;},[readingSaved]);

  const loadGames=useCallback(async(currentMode:'replay'|'live',currentDate:string)=>{
    const result=await api<{games:Game[];feed:Feed}>(`/games?mode=${currentMode}&date=${currentDate.replaceAll('-','')}`);
    setGames(result.games);setFeed(result.feed);if(result.feed.error)setError(`Live feed unavailable. ${result.feed.error}`);return result.games;
  },[]);
  const loadSaved=useCallback(async()=>{try{setSaved(await api<SavedRun[]>('/sessions'));}catch{/* saved list is optional to primary broadcast */}},[]);
  const openSession=useCallback(async(gameId:string,currentMode:'replay'|'live',currentProvider:'demo'|'openai',startIndex=0,currentDate=date)=>{
    const wasSaved=savedRef.current;setBusy(true);setError('');audioRef.current?.clear();setCaptions({});setReadingSaved(false);savedRef.current=false;
    if(socket.current){socket.current.onmessage=null;socket.current.onclose=null;socket.current.close();socket.current=null;}setConnected(false);
    try{
      if(sessionRef.current&&!wasSaved)await post(`/sessions/${sessionRef.current.id}/control`,{action:'stop'}).catch(()=>{});
      const next=await post<Session>('/sessions',{game_id:gameId,mode:currentMode,provider:currentProvider,voice_enabled:true,speed:sessionRef.current?.speed??2,start_index:startIndex,...(currentMode==='live'?{date:currentDate.replaceAll('-','')}: {})});
      seq.current=Math.max(next.seq??0,...(next.events??[]).map(e=>e.seq));epoch.current=next.epoch;setSession(next);sessionRef.current=next;setSelectedGame(gameId);void loadSaved();
    }catch(e){setError((e as Error).message);}finally{setBusy(false);}
  },[loadSaved,date]);
  useEffect(()=>{let alive=true;void(async()=>{
    try{
      const [teamList,configuration,gameList]=await Promise.all([api<Team[]>('/teams'),api<Config>('/config'),loadGames('replay',date)]);
      if(!alive)return;setTeams(teamList);setConfig(configuration);await loadSaved();
      if(gameList.length)await openSession(gameList.find(g=>g.id==='2024_01_BAL_KC')?.id??gameList[0].id,'replay','demo');
    }catch(e){if(alive)setError(`Could not connect to the studio. ${(e as Error).message}`);}finally{if(alive)setLoading(false);}
  })();return()=>{alive=false;};},[]); // Start one local broadcast per page load.

  useEffect(()=>{
    if(!session?.id||readingSaved){setConnected(false);return;}
    let disposed=false,retry:ReturnType<typeof setTimeout>;const id=session.id;
    const connect=()=>{
      if(disposed)return;const ws=new WebSocket(`${location.protocol==='https:'?'wss:':'ws:'}//${location.host}/api/sessions/${id}/stream?since=${seq.current}`);socket.current=ws;
      ws.onopen=()=>{setConnected(true);};
      ws.onmessage=event=>{
        let item:RunEvent;try{item=JSON.parse(event.data);}catch{return;}
        if(item.session_id!==id||item.seq<=seq.current||item.epoch<epoch.current)return;
        const historical=Boolean(item.data.historical||(item as RunEvent&{historical?:boolean}).historical);
        seq.current=item.seq;
        if(item.epoch>epoch.current){epoch.current=item.epoch;audioRef.current?.clear();setCaptions({});}
        setSession(current=>current?reduceEvent(current,item):current);
        if(item.type==='turn'){
          const turn=item.data.turn as Turn;
          if(turn){setCaptions(previous=>{const next={...previous};delete next[turn.id];return next;});}
          if(turn?.mode==='demo'&&!historical)audioRef.current?.demo(turn.spoken_text??turn.text,turn.agent_id,turn.id);
        }
        if(item.type==='turn.start'&&!historical)setCaptions(previous=>({...previous,[String(item.data.turn_id)]:{agent_id:String(item.data.agent_id),persona:String(item.data.persona??(item.data.agent_id==='a'?'Max Carter':'Riley Brooks')),text:''}}));
        if(item.type==='caption.delta'&&!historical)setCaptions(previous=>{const id=String(item.data.turn_id),old=previous[id];return {...previous,[id]:{agent_id:String(item.data.agent_id??old?.agent_id??'a'),persona:old?.persona??(item.data.agent_id==='b'?'Riley Brooks':'Max Carter'),text:String(item.data.text??`${old?.text??''}${item.data.delta??''}`)}};});
        if(item.type==='audio'&&!historical)audioRef.current?.chunk(item.data as unknown as Parameters<BroadcastAudio['chunk']>[0]);
        if(item.type==='segment.sealed'&&!item.data.browser_speech&&!historical)audioRef.current?.seal(item.data as unknown as Parameters<BroadcastAudio['seal']>[0]);
        if(item.type==='error'&&!historical)setError(asText(item.data.message??item.data.error??item.data));
      };
      ws.onclose=()=>{setConnected(false);audioRef.current?.clear();setCaptions({});if(!disposed)retry=setTimeout(connect,1200);};
      ws.onerror=()=>ws.close();
    };
    connect();return()=>{disposed=true;clearTimeout(retry);audioRef.current?.clear();socket.current?.close();};
  },[session?.id,readingSaved]);

  useEffect(()=>{if(mode!=='live')return;const poll=setInterval(()=>{void loadGames(mode,date).catch(e=>setFeed(f=>({...f,status:'error',error:(e as Error).message})));},15000);return()=>clearInterval(poll);},[mode,date,loadGames]);
  useEffect(()=>{transcriptEnd.current?.scrollIntoView({behavior:'smooth',block:'nearest'});},[session?.turns.length]);
  const control=async(action:string,speed?:number)=>{
    if(!session||busy)return;setBusy(true);setError('');
    if(['play','step'].includes(action)&&!muted){await audioRef.current?.unlock();}
    if(['pause','restart','stop'].includes(action))audioRef.current?.clear();
    try{const next=await post<Session>(`/sessions/${session.id}/control`,{action,...(speed?{speed}:{})});if(next.epoch>epoch.current){epoch.current=next.epoch;audioRef.current?.clear();setCaptions({});}setSession(current=>mergeSessionView(current,next));}
    catch(e){setError((e as Error).message);}finally{setBusy(false);}
  };
  const changeMode=async(next:'replay'|'live')=>{if(next===mode&&!readingSaved)return;setBusy(true);setMode(next);setError('');setSelectedTeam(null);audioRef.current?.clear();setCaptions({});try{if(session&&!readingSaved)await post(`/sessions/${session.id}/control`,{action:'stop'});setSession(null);const list=await loadGames(next,date);if(list.length)await openSession(list[0].id,next,provider);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const changeDate=async(next:string)=>{setDate(next);setBusy(true);setError('');audioRef.current?.clear();setCaptions({});try{if(session&&!readingSaved)await post(`/sessions/${session.id}/control`,{action:'stop'});setSession(null);const list=await loadGames('live',next);if(list.length)await openSession(list[0].id,'live',provider,0,next);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const changeProvider=async(next:'demo'|'openai')=>{setProvider(next);if(session)await openSession(selectedGame,mode,next);};
  const toggleVoice=async()=>{const next=!muted;setMuted(next);audioRef.current?.mute(next);if(!next){try{await audioRef.current?.unlock();}catch{setMuted(true);setError('Your browser could not enable audio. Commentary captions are still available.');}}};
  const viewSaved=async(id:string)=>{setBusy(true);audioRef.current?.clear();try{if(session&&!readingSaved)await post(`/sessions/${session.id}/control`,{action:'pause'});const next=await api<Session>(`/sessions/${id}`);setSession(next);sessionRef.current=next;setReadingSaved(true);setHistoryOpen(false);setSelectedGame(next.game.id);setMode(next.mode);setProvider(next.provider);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};

  const game=session?.game??games.find(g=>g.id===selectedGame),snapshot=session?.snapshot,event=snapshot?.event;
  const home=findTeam(game?.home_team),away=findTeam(game?.away_team),playing=session?.status==='playing'||session?.status==='running',stepping=session?.status==='stepping';
  const filteredGames=games.filter(g=>!selectedTeam||[g.home_team,g.away_team].includes(selectedTeam));
  const playEvents=(session?.events??[]).filter(e=>e.type==='snapshot'&&e.seq>=(session?.history_start_seq??0)).map(e=>({seq:e.seq,event:(e.data.snapshot as typeof snapshot)?.event})).filter(item=>item.event).slice(-12).reverse();
  const turns=session?.turns??[],traceEvents=(session?.events??[]).filter(e=>!['audio'].includes(e.type));
  const selectedTrace=traceEvents.find(e=>e.seq===traceSelected)??traceEvents[traceEvents.length-1];
  const sourceFeed=session?.feed??feed,activeFeed={...sourceFeed,last_play_at:sourceFeed.latest_play_at??sourceFeed.last_play_at},lastA=[...turns].reverse().find(t=>t.agent_id==='a'),lastB=[...turns].reverse().find(t=>t.agent_id==='b');
  const progress=session?.total?Math.min(100,session.index/session.total*100):0;
  return <div className="app-shell">
    <header className="site-header"><a className="brand" href="/" aria-label="BanterBots home"><span className="brand-mark">b<span>.</span></span><span>banter<span className="brand-light">bots</span><sup>STUDIO</sup></span></a><nav className="main-nav"><span className="nav-active">Broadcast studio</span><button onClick={()=>{setHistoryOpen(true);void loadSaved();}}><History size={15}/> Saved runs</button></nav><div className="header-right"><span className="connection"><i className={connected?'online':''}/>{connected?'Studio connected':readingSaved?'Recorded session':'Connecting'}</span><button className="icon-button" title="About this studio" aria-label="About this studio" onClick={()=>setHelp(true)}><Settings2 size={18}/></button><div className="user-icon">BB</div></div></header>
    <section className="team-ribbon" aria-label="Filter games by NFL team"><button className={`all-teams ${!selectedTeam?'selected':''}`} onClick={()=>setSelectedTeam(null)}>ALL<br/><strong>32</strong></button><div className="team-list">{teams.map(team=><button key={team.id} className={`team-option ${selectedTeam===team.id?'selected':''}`} title={team.name} aria-label={`Filter ${team.name}`} aria-pressed={selectedTeam===team.id} onClick={()=>setSelectedTeam(selectedTeam===team.id?null:team.id)}><Logo team={team} size={31}/><span>{team.abbreviation}</span></button>)}{!teams.length&&Array.from({length:20},(_,i)=><div className="logo-skeleton" key={i}/>)}</div><span className="league-label">NFL <ChevronDown size={13}/></span></section>
    <section className="score-ribbon" aria-label="Game ticker"><div className="ticker-label"><Radio size={15}/><span>{mode==='replay'?'THE REPLAY ROOM':'AROUND THE LEAGUE'}</span></div><div className="score-list">{filteredGames.map(item=><button key={item.id} className={`mini-game ${selectedGame===item.id?'selected':''}`} onClick={()=>void openSession(item.id,mode,provider)} disabled={busy}><span className="mini-teams"><span><Logo team={findTeam(item.away_team)} size={21}/><b>{item.away_team}</b><strong>{item.away_score}</strong></span><span><Logo team={findTeam(item.home_team)} size={21}/><b>{item.home_team}</b><strong>{item.home_score}</strong></span></span><span className="mini-status">{item.mode==='replay'?new Date(item.start_time).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}):item.status}<ChevronRight size={12}/></span></button>)}{!filteredGames.length&&<span className="ticker-empty">{selectedTeam?'No games for this team in this feed.':'No live games found for this date. Switch to Replay to enter the studio.'}</span>}</div><div className="ticker-source"><Layers size={14}/>{mode==='replay'?'nflverse data':'ESPN feed'}</div></section>
    <main className="main-content">
      <div className="page-title"><div><div className="eyebrow"><span/> TWO SIDES. ONE GAME.</div><h1>The rivalry is <em>live.</em></h1><p>A little football. A lot of opinions. Your two-agent commentary booth.</p></div><div className="page-actions"><div className="mode-switch" aria-label="Feed mode"><button className={mode==='replay'?'active':''} onClick={()=>void changeMode('replay')} disabled={busy}><History size={14}/> Replay</button><button className={mode==='live'?'active':''} onClick={()=>void changeMode('live')} disabled={busy}><Radio size={14}/> Live feed</button></div><button className={`debug-button ${debug?'active':''}`} onClick={()=>setDebug(!debug)}><Code2 size={16}/> Agent debugger<span>{debug?'ON':'OFF'}</span></button></div></div>
      {error&&<div className="error-banner" role="alert"><WifiOff size={17}/><span>{error}</span><button aria-label="Dismiss error" onClick={()=>setError('')}><X size={17}/></button></div>}
      {loading&&<div className="loading-banner"><LoaderCircle size={16} className="spin"/> Preparing the studio and loading real NFL play-by-play…</div>}
      {readingSaved&&<div className="saved-banner"><History size={16}/><span>Recorded run • Playback is silent. This view shows the original results.</span><button onClick={()=>void openSession(selectedGame,mode,provider)}>Regenerate as a new run <ArrowRight size={14}/></button></div>}
      <div className="studio-grid">
        <div className="game-column">
          <section className="panel game-panel"><div className="panel-header"><span><i className={`status-dot ${playing?'live':''}`}/>{mode==='replay'?'HISTORICAL REPLAY':'LIVE GAME'}</span><span className="pill subtle">{mode==='replay'?'REAL GAME DATA':'POLLING · 5 SEC'}</span></div>
            <div className="game-selector"><label htmlFor="game">IN THE BOOTH</label><select id="game" value={selectedGame} disabled={busy||!filteredGames.length} onChange={e=>void openSession(e.target.value,mode,provider)}>{filteredGames.map(g=><option value={g.id} key={g.id}>{g.away_team} at {g.home_team} · {g.label||new Date(g.start_time).toLocaleDateString()}</option>)}{!filteredGames.length&&<option value={selectedGame}>No games available</option>}</select>{mode==='live'&&<input aria-label="Live games date" type="date" value={date} disabled={busy} onChange={e=>void changeDate(e.target.value)}/>}</div>
            <div className="matchup"><div className="matchup-team" style={teamColor(away)}><Logo team={away} size={79}/><h2>{away?.abbreviation??game?.away_team??'AWAY'}</h2><span>{away?.name?.replace(/.*(?=\s(?:Ravens|Chiefs|Eagles)$)/,'').trim()??'Away team'}</span><i className="support-tag">RILEY’S SIDE</i></div><div className="matchup-score"><span className="score-kicker">{event?`Q${event.quarter} · ${event.clock}`:'READY FOR KICKOFF'}</span><div><strong>{event?.away_score??(mode==='live'?game?.away_score:0)??0}</strong><span>:</span><strong>{event?.home_score??(mode==='live'?game?.home_score:0)??0}</strong></div><span className="matchup-state">{session?.status==='completed'?'REPLAY COMPLETE':playing?'ON AIR':readingSaved?'RECORDED':'BOOTH STANDBY'}</span></div><div className="matchup-team" style={teamColor(home)}><Logo team={home} size={79}/><h2>{home?.abbreviation??game?.home_team??'HOME'}</h2><span>{home?.name?.replace(/.*(?=\s(?:Ravens|Chiefs|Eagles)$)/,'').trim()??'Home team'}</span><i className="support-tag">MAX’S SIDE</i></div></div>
            <div className="game-facts"><div><span>POSSESSION</span><b>{event?.possession??'—'}{event?.possession&&<span className="football-dot"/>}</b></div><div><span>DOWN & DISTANCE</span><b>{event?.down?`${ordinal(event.down)} & ${event.distance??'—'}`:'—'}</b></div><div><span>FIELD POSITION</span><b>{event?.yardline!=null?`${event.yardline} YDS`:'—'}</b></div></div>
            <div className="football-field" aria-label={event?.yardline!=null?`Ball ${event.yardline} yards from goal`:'Football field waiting for next play'}><div className="endzone">{game?.away_team??'NFL'}</div><div className="yard-grid">{Array.from({length:9},(_,i)=><span key={i}>{i<5?(i+1)*10:(9-i)*10}</span>)}{event?.yardline!=null&&<div className="ball-marker" style={{left:`${Math.max(2,Math.min(98,100-event.yardline))}%`}}><span/> <b>{event.possession}</b></div>}</div><div className="endzone">{game?.home_team??'NFL'}</div></div>
            <div className="current-play"><span className="eyebrow">{event?'LATEST PLAY':'THE STAGE IS SET'}</span><p>{event?.description??'Press play to relive the game, one real play at a time. Max and Riley have a few things to say.'}</p></div>
            <div className="transport"><button className={`play-button ${playing?'is-playing':''}`} disabled={busy||!session||readingSaved||stepping||session.status==='completed'} onClick={()=>void control(playing?'pause':'play')}>{busy||stepping?<LoaderCircle size={16} className="spin"/>:playing?<Pause size={16} fill="currentColor"/>:<Play size={16} fill="currentColor"/>}{playing?'Pause broadcast':stepping?'Calling this play…':'Start broadcast'}</button><button className="icon-button outlined" disabled={busy||!session||readingSaved||playing||stepping||session.status==='completed'} onClick={()=>void control('step')} aria-label="Advance one play" title="Advance one play"><SkipForward size={17}/></button><button className="icon-button outlined" disabled={busy||!session||readingSaved} onClick={()=>void control('restart')} aria-label="Restart game" title="Restart game"><RotateCcw size={16}/></button><label className="speed-label" title="Replay speed">{mode==='replay'&&<><Zap size={13}/><select aria-label="Replay speed" value={session?.speed??2} disabled={busy||readingSaved} onChange={e=>void control('speed',Number(e.target.value))}><option value={.5}>0.5×</option><option value={1}>1×</option><option value={2}>2×</option><option value={4}>4×</option><option value={8}>8×</option></select></>}</label></div>
            <div className="replay-progress"><div><i style={{width:`${progress}%`}}/></div><span>{mode==='replay'?`PLAY ${Math.min((session?.index??0)+1,session?.total??0)} OF ${session?.total??'—'}`:`FEED ${activeFeed.status.toUpperCase()}`}</span><span>{mode==='replay'?'2024 NFL SEASON':`POLLED ${time(activeFeed.last_success)}`}</span></div>
          </section>
          <section className="panel playfeed-panel"><div className="panel-header"><span><Activity size={14}/> PLAY-BY-PLAY</span><span className="small-muted">Shared by both agents</span></div><div className="play-feed">{playEvents.length?playEvents.map(({seq:playSeq,event:play},i)=><div className={`play-feed-item ${i===0?'latest':''}`} key={playSeq}><div className="play-stamp">Q{play!.quarter}<span>{play!.clock}</span></div><div><span className={`play-type ${play!.flags?.some(f=>f.includes('touchdown'))?'scoring':''}`}>{play!.play_type.replaceAll('_',' ')}{play!.revision>1?' · CORRECTED':''}</span><p>{play!.description}</p></div></div>):<div className="feed-empty"><Activity size={23}/><p>The playbook is ready.</p><span>Game events appear here as the broadcast unfolds.</span></div>}</div><div className="feed-health"><span><Wifi size={12}/>{mode==='replay'?'Verified nflverse replay':`Feed: ${activeFeed.status}`}</span><span>{mode==='replay'?'No future plays shared':`Last play ${time(activeFeed.last_play_at??event?.occurred_at)}`}</span></div></section>
        </div>
        <div className="booth-column">
          <section className="panel booth-panel"><div className="panel-header"><span><Mic size={15}/> THE COMMENTARY BOOTH</span><button className={`voice-control ${!muted?'enabled':''}`} onClick={()=>void toggleVoice()} aria-pressed={!muted}>{muted?<VolumeX size={15}/>:<Volume2 size={15}/>}Voice {muted?'off':'on'}</button></div><div className="persona-grid">{(['a','b'] as const).map((agent,i)=>{const team=i===0?home:away,persona=config?.personas.find(p=>p.agent_id===agent),last=i===0?lastA:lastB,active=speaking===agent;return <div className={`persona-card ${active?'speaking':''}`} style={teamColor(team)} key={agent}><div className="persona-top"><div className={`persona-avatar persona-${agent}`}><Mic size={23}/><span>{agent==='a'?'MC':'RB'}</span></div><span className="agent-badge">AGENT {agent.toUpperCase()}<i/></span></div><h3>{persona?.name??(i===0?'Max Carter':'Riley Brooks')}</h3><p>{i===0?'The heart-on-his-sleeve hype man.':'The dry wit. The tactical eye.'}</p><div className="persona-team"><Logo team={team} size={22}/><span>Backing the <strong>{team?.abbreviation??(i===0?'home':'away')} {i===0?'home':'away'} team</strong></span></div><div className="persona-footer"><Wave active={active}/><span>{active?'ON THE MIC':last?'LISTENING':'READY TO TALK'}</span></div></div>;})}</div><div className="booth-flow"><span><ShieldCheck size={13}/> Same game facts</span><i/><span><MessageCircle size={13}/> Real A2A exchange</span><i/><span>Two rival perspectives</span></div></section>
          <section className="panel conversation-panel">
            <div className="panel-header"><span><MessageCircle size={15}/> LIVE CONVERSATION <b className="count">{turns.length}</b></span><span className={`pill ${provider==='demo'?'demo':'subtle'}`}>{provider==='demo'?'DEMO COMMENTARY':'GPT-LIVE AUDIO'}</span></div>
            <div className="conversation" aria-live="polite" aria-label="Agent commentary transcript">
              {turns.length?turns.map((turn,i)=><article className={`commentary-turn agent-${turn.agent_id} ${speaking===turn.agent_id&&i===turns.length-1?'talking':''}`} key={turn.id} style={teamColor(findTeam(turn.team_id))}><div className="turn-avatar">{turn.agent_id==='a'?'M':'R'}</div><div className="turn-body"><div className="turn-meta"><strong>{turn.persona}</strong><span className="turn-team">{turn.team_id}</span><span className="turn-kind">{turn.reply_to_turn_id?<><ArrowDown size={10}/> THE REPLY</>:'THE CALL'}</span><time>{time(turn.created_at)}</time></div><p>{turn.mode==='openai'?turn.spoken_text??turn.text:turn.text}</p><div className="turn-proof"><Check size={11}/><span>Play {turn.event_id.split('_').pop()} · snapshot {turn.snapshot_hash.slice(0,8)}</span></div></div></article>):!Object.values(captions).some(c=>c.text)&&<div className="conversation-empty"><div className="empty-mics"><div><Mic size={27}/></div><span>vs.</span><div><Mic size={27}/></div></div><h3>Great rivals make great radio.</h3><p>Start the broadcast. Two personalities will trade calls,<br/>challenge each other, and bring every play to life.</p><div><span><i/> MAX CARTER</span><span><i/> RILEY BROOKS</span></div></div>}
              {Object.entries(captions).filter(([,caption])=>caption.text).map(([id,caption])=><article className={`commentary-turn agent-${caption.agent_id} talking`} key={id}><div className="turn-avatar">{caption.agent_id==='a'?'M':'R'}</div><div className="turn-body"><div className="turn-meta"><strong>{caption.persona}</strong><span className="turn-kind">ON THE MIC</span></div><p>{caption.text}<span className="caption-cursor"/></p></div></article>)}
              {playing&&!speaking&&<div className="thinking"><i/><i/><i/><span>Reading the field…</span></div>}<div ref={transcriptEnd}/>
            </div>
            <div className="conversation-footer"><span><i className={playing?'live':''}/>{readingSaved?'Original transcript':playing?'Agents are on air':'The booth is waiting'}</span><span>{muted?'Captions only':'Captions + voice'} <Mic size={12}/></span></div>
          </section>
          <section className="architecture-bar"><div className="architecture-icon"><Layers size={17}/></div><div><strong>Built for chemistry. Grounded in facts.</strong><span>LangGraph orchestration <i>·</i> A2A {config?.a2a_version??'1.0'} <i>·</i> Causal game snapshots</span></div><button aria-label="Open agent debugger" onClick={()=>setDebug(true)}><ArrowRight size={18}/></button></section>
        </div>
      </div>
      <section className="studio-status"><div><span className="eyebrow">ENGINE ROOM</span><select aria-label="Commentary provider" value={provider} disabled={busy||playing||readingSaved} onChange={e=>void changeProvider(e.target.value as typeof provider)}><option value="demo">Demo · no API key needed</option><option value="openai" disabled={!config?.openai_configured}>OpenAI · {config?.openai_configured?'connected':'add credentials to enable'}</option></select></div><div className="engine-metrics"><span>Text latency <strong>{duration(session?.metrics.first_text_ms??session?.metrics.ingestion_to_first_text_ms)}</strong></span><span>Audio latency <strong>{duration(session?.metrics.first_audio_ms??session?.metrics.ingestion_to_first_audio_ms)}</strong></span><span>Peer exchanges <strong>{turns.filter(t=>t.reply_to_turn_id).length}</strong></span></div></section>
      {debug&&<section className="panel debugger"><div className="panel-header"><span><Terminal size={16}/> AGENT DEBUGGER <span className="debug-version">LangGraph / A2A {config?.a2a_version??'1.0'}</span></span><div><a className="export-link" href={session?`/api/sessions/${session.id}/export`:'#'} download={`banterbots-${session?.id}.json`}><Download size={13}/> Export trace</a><button className="icon-button" aria-label="Close debugger" onClick={()=>setDebug(false)}><X size={15}/></button></div></div><div className="debug-tabs">{['timeline','shared facts','prompts & outputs','metrics'].map(tab=><button key={tab} className={debugTab===tab?'active':''} onClick={()=>setDebugTab(tab)}>{tab}</button>)}</div>{debugTab==='timeline'?<div className="trace-grid"><div className="trace-list">{traceEvents.slice(-80).reverse().map(trace=><button key={trace.seq} className={selectedTrace?.seq===trace.seq?'active':''} onClick={()=>setTraceSelected(trace.seq)}><span className={`trace-kind ${trace.type==='error'?'error':''}`}>{trace.type}</span><span>{asText(trace.data.node??trace.data.stage??trace.data.message??'').slice(0,65)}</span><time>{time(trace.timestamp)}</time></button>)}{!traceEvents.length&&<p>No trace events yet. Advance a play to inspect the graph.</p>}</div><pre>{selectedTrace?JSON.stringify(selectedTrace,null,2):'The selected event will appear here.'}</pre></div>:debugTab==='shared facts'?<pre>{JSON.stringify(snapshot??{message:'No snapshot yet. Both agents receive the exact same sealed snapshot.'},null,2)}</pre>:debugTab==='prompts & outputs'?<div className="prompt-list">{traceEvents.filter(e=>e.type.includes('prompt')||e.type==='turn'||e.type==='trace'&&JSON.stringify(e.data).includes('prompt')).slice(-25).map(e=><details key={e.seq}><summary>{e.type} · {asText(e.data.node??e.data.agent_id??(e.data.turn as Turn)?.persona??'agent')}<span>{time(e.timestamp)}</span></summary><pre>{JSON.stringify(e.data,null,2)}</pre></details>)}{!traceEvents.some(e=>e.type==='turn')&&<p>Agent prompts and generated outputs appear here after a play.</p>}</div>:<pre>{JSON.stringify({session_id:session?.id,epoch:session?.epoch,status:session?.status,metrics:session?.metrics,feed:activeFeed,transport:connected?'WebSocket connected':'Disconnected',text_model:config?.text_model,voice_model:config?.voice_model},null,2)}</pre>}</section>}
      <footer className="footer"><span><span className="footer-brand">banterbots.</span> A rivalry worth listening to.</span><span>Historical data: <a href="https://github.com/nflverse/nflverse-data" target="_blank" rel="noreferrer">nflverse <ExternalLink size={10}/></a><i>·</i> POC STUDIO v0.1</span></footer>
    </main>
    {historyOpen&&<div className="modal-backdrop" onClick={()=>setHistoryOpen(false)}><section className="modal" role="dialog" aria-modal="true" aria-label="Saved broadcasts" onClick={e=>e.stopPropagation()}><div className="modal-title"><h2>Saved broadcasts</h2><button className="icon-button" aria-label="Close saved broadcasts" onClick={()=>setHistoryOpen(false)}><X size={19}/></button></div><p>Inspect the original conversation and traces. Reopening a run never regenerates commentary.</p><div className="saved-list">{saved.length?saved.map(run=><button key={run.id} onClick={()=>void viewSaved(run.id)} disabled={busy}><div><History size={18}/><span><strong>{run.game?`${run.game.away_team} at ${run.game.home_team}`:run.game_id??run.id.slice(0,8)}</strong><small>{run.created_at?new Date(run.created_at).toLocaleString():run.id.slice(0,12)} · {run.mode} · {run.provider}</small></span></div><span>{run.status} <ChevronRight size={15}/></span></button>):<div className="feed-empty"><History size={24}/><p>No saved broadcasts yet.</p></div>}</div></section></div>}
    {help&&<div className="modal-backdrop" onClick={()=>setHelp(false)}><section className="modal" role="dialog" aria-modal="true" aria-label="About BanterBots" onClick={e=>e.stopPropagation()}><div className="modal-title"><h2>Your commentary studio</h2><button className="icon-button" aria-label="Close studio information" onClick={()=>setHelp(false)}><X size={19}/></button></div><p>Max backs the home team. Riley backs the visitors. Both see one frozen game snapshot, then trade a call and a reply through A2A.</p><div className="help-step"><Play size={19}/><span><strong>Enter the replay room</strong>Choose a real game and press Start broadcast. Use Next play to inspect a single exchange.</span></div><div className="help-step"><Volume2 size={19}/><span><strong>Turn up the rivalry</strong>Enable voice. Demo commentary uses browser voices; OpenAI mode streams GPT-Live audio after credentials are configured.</span></div><div className="help-step"><Code2 size={19}/><span><strong>Follow every handoff</strong>Open the debugger for graph stages, A2A payloads, prompt context, errors, and correlated traces.</span></div><div className="help-note">Live scores use ESPN’s polling feed. Poll time and latest-play time are reported separately. Demo speech is intentionally labelled.</div></section></div>}
  </div>;
}
export default App;
